general:
  name: NameFromConfig
  base_path: /tmp/lean_eth_node
  modules_dir: modules

database:
  directory: db
  cache_size: 1G

metrics:
  enabled: true
  host: 127.0.0.1
  port: 9615

logging:
  sinks:
    - name: console
      type: console
      stream: stdout
      thread: name
      color: true
      latency: 0
  groups:
    - name: main
      sink: console
      level: info
      is_fallback: true
      children:
        - name: lean
          children:
            - name: modules
              children:
                - name: example_module
                - name: synchronizer_module
                - name: networking_module
                - name: production_module
            - name: injector
            - name: application
            - name: rpc
            - name: metrics
            - name: threads
            - name: storage
              children:
                - name: block_storage
            - name: blockchain
              children:
                - name: block_tree
                - name: fork_choice
                  level: trace