# Genesis Settings
GENESIS_TIME: 1764685602
# Key Settings
ACTIVE_EPOCH: 18
# Validator Settings  
VALIDATOR_COUNT: 4
GENESIS_VALIDATORS:
  - "b3183808a14d1875748fd96989441855092ef73c6bf5a7680f03b32d1c12f96ec4659e64fd526f3d975eb168907ee7589946f972"
  - "d89fef7b41821a67c118e26808f48e28d00cbe082a1f88369b8828147f3905656b3b04785a5b26403a0c0a574b4f333bd4d48a03"
  - "d404bb1091a750710952a64b22240d0013bcc66a64b5b1780b89b120c0dd7d212fa3cb5e42f56e74fcc68950e6b493647524a627"
  - "b196071b88a6f16d658e512f753be6222e54e91a19e0d676201ac5161cd90e1e40210d36e024f81ae30ee67714092009c20b415c"
